language: go
go:
  - 1.3.1
  - 1.3.3
  - 1.4.2
env:
  - GOARCH: amd64
  - GOARCH: 386
notifications:
  email:
    recipients:
      - brian.downs@gmail.com
    on_success: change
    on_failure: always
